GGinfoSite/Controllers/BlogController.cs
using GGinfoSite.Data;
using GGinfoSite.Models;
using GGinfoSite.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GGinfoSite.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        IBlogPostRepository repo;
        private UserManager<AppUser> userManager;
        private SignInManager<AppUser> signInManager;

        public BlogController(UserManager<AppUser> userMngr,
            SignInManager<AppUser> signInMngr, IBlogPostRepository r)
        {
            userManager = userMngr;
            signInManager = signInMngr;
            repo = r;
        }

        public async Task<IActionResult> Index()
        {
            var blogPosts = await repo.GetBlogPostsQuery().Include(bp => bp.Comments)
                .ThenInclude(c => c.Commenter).ToListAsync();
            return View(blogPosts);
        }

        public async Task<IActionResult> Filter(string poster, string date)
        {
            var blogPostsQuery = repo.GetBlogPostsQuery().Include(bp => bp.Comments);
            var blogPosts = await blogPostsQuery.ToListAsync();
            var filteredBlogPosts = blogPosts.Where(b => b.Poster.UserName == poster || poster == null).ToList();

            return View("Index", filteredBlogPosts);
        }


        public IActionResult About()
        {
            return View();
        }

        public IActionResult BlogPost()
        {
            return View();
        }

        public IActionResult Comment(int blogPostID)
        {
            var commentVM = new CommentVM { BlogPostID = blogPostID };
            return View(commentVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comment(CommentVM commentVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Comment", commentVM);
            }

            //extract comment from VM
            var comment = new Comment { CommentText = commentVM.CommentText, BlogPostID = commentVM.BlogPostID }; 
            comment.Commenter = userManager.GetUserAsync(User).Result;
            comment.CommentDate = DateTime.Now;
            await repo.StoreCommentAsync(comment);

            //grab parent blogpost
            var blogPost = await repo.GetBlogPostByIdAsync(commentVM.BlogPostID);

            //assign comment to post
            blogPost.Comments.Add(comment);
            await repo.UpdateBlogPostAsync(blogPost);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBlogPostAsync(BlogPost model)
        {
            if (!ModelState.IsValid)
            {
                return View("BlogPost", model);
            }

            model.Poster = await userManager.GetUserAsync(User);
            model.PostTime = DateTime.Now;

            await repo.AddBlogPostAsync(model);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteComment(int commentID)
        {
            repo.DeleteComment(commentID);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteBlogPost(int blogPostID)
        {
            repo.DeleteBlogPost(blogPostID);
            return RedirectToAction("Index");
        }
    }
}

GGinfoSite/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace GGinfoSite.Controllers
{
    public class HistoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GGinfoSite/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using GGinfoSite.Models;
using GGinfoSite.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlTypes;

namespace GGinfoSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private UserManager<AppUser> userManager;
        private RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<AppUser> userMngr, RoleManager<IdentityRole> roleMngr)
        {
            userManager = userMngr;
            roleManager = roleMngr;
        }

        public IActionResult Index()
        {
            List<AppUser> users = new List<AppUser>();
            users = userManager.Users.ToList();

            foreach (AppUser user in users)
            {
                var task = userManager.GetRolesAsync(user);
                task.Wait();
                user.RoleNames = task.Result;
            }

            UserViewModel model = new UserViewModel
            {
                Users = users,
                Roles = roleManager.Roles
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Username };
                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                try
                {
                    IdentityResult result = await userManager.DeleteAsync(user);
                    if (!result.Succeeded)
                    {
                        string errorMessage = "";
                        foreach (IdentityError error in result.Errors)
                        {
                            errorMessage += error.Description + " | ";
                        }
                        TempData["message"] = errorMessage;
                    }
                    else
                    {
                        TempData["SuccessMessage"] = "User deleted successfully.";
                    }
                }
                catch (DbUpdateException ex)
                {
                    if(ex.InnerException != null && ex.InnerException.Message.Contains("foreign key"))
                    {
                        TempData["ErrorMessage"] = "User cannot be deleted, as they are referenced in other records.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "An unexpected error occured while deleing the user.";
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole = await roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. " + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                AppUser user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Admin"));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
    }
}

GGinfoSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GGinfoSite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" 
        integrity="sha-long-hash_code" crossorigin="anonymous"/>
</head>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cafe Chronicles</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" 
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="About">About</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="User" asp-action="Index">
                                        <span class="fas fa-cog"></span>&nbsp;Admin
                                    </a>
                                </li>
                            }
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <input type="submit" value="Log Out" class="btn btn-outline-dark" />
                                    <span class="text-dark">@User.Identity.Name</span>
                                </form>
                            </li>
                        }
                        else
                        {
                            var action = ViewContext.RouteData.Values["action"]?.ToString();
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">
                                    <span class="fas fa-edit"></span> &nbsp; Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Login" asp-controller="Account" class="btn btn-outline-dark">Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Cafe Chronicles
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>